### ISSUE TITLE
Organization Name

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang.github.io#3]
@vavr we need your support in order to change our organization name to "vavr". Could you help us by changing your Github name, e.g. to "vavrjin"?

Currently our website is down. Please giver us a short reply/feedback.

**Comment by vavr** [comment]
I can give you an answer at Monday. Sorry cant do it earlier...

15 апр. 2017 г. 7:21 PM пользователь "Daniel Dietrich" <
notifications@github.com> написал:

**Comment by danieldietrich** [comment]
@vavr Great, thank you for your reply! (btw - cool name ;)

**Comment by danieldietrich** [comment]
Hi @vavr,

I will register "vavr" as a trademark soon.

![vavr](https://cloud.githubusercontent.com/assets/743833/25082939/28ceff9e-2354-11e7-9e89-fd950d6a8ecf.png)

There are many conference talks: http://github.com/vavr-io/resources

It would be really great if you could release the name!

**Comment by danieldietrich** [comment]
@vavr Do you have decided, yet? If you say no it is ok, I understand.
I need a short reply because I want to setup our chatrooms now and need the final Github name.
Thank you!

**Comment by vavr** [comment]
Sorry, i dont want to change my name :( think you understood me

19 апр. 2017 г. 5:44 PM пользователь "Daniel Dietrich" <
notifications@github.com> написал:

**Comment by danieldietrich** [comment]
@vavr Ok, thanks! I think I would do the same.
